# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\Desktop\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gl_sys = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.gl_sys.setGeometry(QtCore.QRect(460, 20, 671, 671))
        self.gl_sys.setObjectName("gl_sys")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(60, 230, 131, 41))
        self.add_button.setObjectName("add_button")
        self.add_random_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_random_button.setGeometry(QtCore.QRect(220, 230, 200, 41))
        self.add_random_button.setObjectName("add_random_button")
        self.v_x_label = QtWidgets.QLabel(self.centralwidget)
        self.v_x_label.setGeometry(QtCore.QRect(20, 60, 71, 31))
        self.v_x_label.setObjectName("v_x_label")
        self.v_y_label = QtWidgets.QLabel(self.centralwidget)
        self.v_y_label.setGeometry(QtCore.QRect(20, 100, 71, 31))
        self.v_y_label.setObjectName("v_y_label")
        self.v_z_label = QtWidgets.QLabel(self.centralwidget)
        self.v_z_label.setGeometry(QtCore.QRect(20, 140, 71, 31))
        self.v_z_label.setObjectName("v_z_label")
        self.v_x = QtWidgets.QTextEdit(self.centralwidget)
        self.v_x.setGeometry(QtCore.QRect(100, 60, 104, 31))
        self.v_x.setObjectName("v_x")
        self.v_y = QtWidgets.QTextEdit(self.centralwidget)
        self.v_y.setGeometry(QtCore.QRect(100, 100, 104, 31))
        self.v_y.setObjectName("v_y")
        self.v_z = QtWidgets.QTextEdit(self.centralwidget)
        self.v_z.setGeometry(QtCore.QRect(100, 140, 104, 31))
        self.v_z.setObjectName("v_z")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(240, 20, 91, 31))
        self.time_label.setObjectName("time_label")
        self.time = QtWidgets.QTextEdit(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(340, 20, 104, 31))
        self.time.setObjectName("time")
        self.c_x_label = QtWidgets.QLabel(self.centralwidget)
        self.c_x_label.setGeometry(QtCore.QRect(240, 60, 91, 31))
        self.c_x_label.setObjectName("c_x_label")
        self.c_x = QtWidgets.QTextEdit(self.centralwidget)
        self.c_x.setGeometry(QtCore.QRect(340, 60, 104, 31))
        self.c_x.setObjectName("c_x")
        self.c_y_label = QtWidgets.QLabel(self.centralwidget)
        self.c_y_label.setGeometry(QtCore.QRect(240, 100, 91, 31))
        self.c_y_label.setObjectName("c_y_label")
        self.c_y = QtWidgets.QTextEdit(self.centralwidget)
        self.c_y.setGeometry(QtCore.QRect(340, 100, 104, 31))
        self.c_y.setObjectName("c_y")
        self.c_z_label = QtWidgets.QLabel(self.centralwidget)
        self.c_z_label.setGeometry(QtCore.QRect(240, 140, 91, 31))
        self.c_z_label.setObjectName("c_z_label")
        self.c_z = QtWidgets.QTextEdit(self.centralwidget)
        self.c_z.setGeometry(QtCore.QRect(340, 140, 104, 31))
        self.c_z.setObjectName("c_z")
        self.parametrs_part = QtWidgets.QLabel(self.centralwidget)
        self.parametrs_part.setGeometry(QtCore.QRect(14, 10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.parametrs_part.setFont(font)
        self.parametrs_part.setObjectName("parametrs_part")

        self.color_test = QtWidgets.QWidget(self.centralwidget)
        self.color_test.setGeometry(QtCore.QRect(280, 180, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 153, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 180, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 76, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 102, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 153, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 153, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 180, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 76, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 102, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 153, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 76, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 153, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 180, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 76, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 102, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 76, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 76, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 153, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 153, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 153, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.color_test.setPalette(palette)
        self.color_test.setAutoFillBackground(True)
        self.color_test.setObjectName("color_test")

        self.mass = QtWidgets.QTextEdit(self.centralwidget)
        self.mass.setGeometry(QtCore.QRect(100, 180, 104, 31))
        self.mass.setObjectName("mass")
        self.mass_label = QtWidgets.QLabel(self.centralwidget)
        self.mass_label.setGeometry(QtCore.QRect(20, 180, 71, 31))
        self.mass_label.setObjectName("mass_label")
        self.color_label = QtWidgets.QLabel(self.centralwidget)
        self.color_label.setGeometry(QtCore.QRect(240, 180, 71, 31))
        self.color_label.setObjectName("color_label")
        self.method_combo = QtWidgets.QComboBox(self.centralwidget)
        self.method_combo.setGeometry(QtCore.QRect(80, 340, 131, 31))
        self.method_combo.setObjectName("method_combo")
        self.method_combo.addItem("")
        self.method_combo.addItem("")
        self.alg_label = QtWidgets.QLabel(self.centralwidget)
        self.alg_label.setGeometry(QtCore.QRect(20, 340, 71, 31))
        self.alg_label.setObjectName("alg_label")
        self.count_label = QtWidgets.QLabel(self.centralwidget)
        self.count_label.setGeometry(QtCore.QRect(20, 390, 121, 31))
        self.count_label.setObjectName("count_label")
        self.count_combo = QtWidgets.QComboBox(self.centralwidget)
        self.count_combo.setGeometry(QtCore.QRect(140, 390, 131, 31))
        self.count_combo.setObjectName("count_combo")
        self.count_combo.addItem("")
        self.count_combo.addItem("")
        self.count_combo.addItem("")
        self.count_combo.addItem("")
        self.count_combo.addItem("")
        self.count_combo.addItem("")
        self.param_sys = QtWidgets.QLabel(self.centralwidget)
        self.param_sys.setGeometry(QtCore.QRect(140, 280, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.param_sys.setFont(font)
        self.param_sys.setObjectName("param_sys")
        self.cur_count_label = QtWidgets.QLabel(self.centralwidget)
        self.cur_count_label.setGeometry(QtCore.QRect(20, 430, 171, 31))
        self.cur_count_label.setObjectName("cur_count_label")
        self.cur_count = QtWidgets.QLabel(self.centralwidget)
        self.cur_count.setGeometry(QtCore.QRect(200, 430, 21, 31))
        self.cur_count.setObjectName("cur_count")
        self.color_button = QtWidgets.QPushButton(self.centralwidget)
        self.color_button.setGeometry(QtCore.QRect(330, 180, 121, 31))
        self.color_button.setObjectName("color_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.c_x.setText(str(random.randint(-1000,1000)))
        self.c_y.setText(str(random.randint(-1000,1000)))
        self.c_z.setText(str(random.randint(-1000,1000)))
        self.time.setText(str(random.randint(10, 1000)))
        self.v_x.setText(str(random.randint(-5,5)))
        self.v_y.setText(str(random.randint(-5,5)))
        self.v_z.setText(str(random.randint(-5,5)))
        self.mass.setText(str(random.randint(100,1000)))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_button.setText(_translate("MainWindow", "Добавить частицу"))
        self.add_random_button.setText(_translate("MainWindow", "Добавить случайную частицу"))
        self.v_x_label.setText(_translate("MainWindow", "Скорость X"))
        self.v_y_label.setText(_translate("MainWindow", "Скорость Y"))
        self.v_z_label.setText(_translate("MainWindow", "Скорость Z"))
        self.time_label.setText(_translate("MainWindow", "Время"))
        self.c_x_label.setText(_translate("MainWindow", "Координата X"))
        self.c_y_label.setText(_translate("MainWindow", "Координата Y"))
        self.c_z_label.setText(_translate("MainWindow", "Координата Z"))
        self.parametrs_part.setText(_translate("MainWindow", "Параметры частицы"))
        self.mass_label.setText(_translate("MainWindow", "Масса"))
        self.color_label.setText(_translate("MainWindow", "Цвет"))
        self.method_combo.setItemText(0, _translate("MainWindow", "Верле"))
        self.method_combo.setItemText(1, _translate("MainWindow", "odeint Верле"))
 
        self.alg_label.setText(_translate("MainWindow", "Алгоритм"))
        self.count_label.setText(_translate("MainWindow", "Количество частиц"))
        self.count_combo.setItemText(0, _translate("MainWindow", "100"))
        self.count_combo.setItemText(1, _translate("MainWindow", "200"))
        self.count_combo.setItemText(2, _translate("MainWindow", "500"))
        self.count_combo.setItemText(3, _translate("MainWindow", "1000"))
        self.count_combo.setItemText(4, _translate("MainWindow", "Пользовательское число"))
        self.count_combo.setItemText(5, _translate("MainWindow", "Солнечная система"))
        self.param_sys.setText(_translate("MainWindow", "Параметры системы"))
        self.cur_count_label.setText(_translate("MainWindow", "Текущее количество частиц"))
        self.cur_count.setText(_translate("MainWindow", "0"))
        self.color_button.setText(_translate("MainWindow", "Выбрать цвет"))